
// This file was generated by [tauri-specta](https://github.com/specta-rs/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getYtmusicCookies(label: string) : Promise<null> {
    return await TAURI_INVOKE<null>("get_ytmusic_cookies", { label });
},
async instanceYtmusicApi(cookies: string) : Promise<null> {
    return await TAURI_INVOKE<null>("instance_ytmusic_api", { cookies });
},
async logoutYtmusic() : Promise<null> {
    return await TAURI_INVOKE<null>("logout_ytmusic");
},
async getAllPlaylists() : Promise<Playlist[]> {
    return await TAURI_INVOKE<Playlist[]>("get_all_playlists");
},
async getSongsFromPlaylist(playlistId: string, offset: number | null, limit: number | null) : Promise<Song[]> {
    return await TAURI_INVOKE<Song[]>("get_songs_from_playlist", { playlistId, offset, limit });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Album = { name: string; id: string }
export type Artist = { name: string; id: string }
export type Duration = { secs: number; nanos: number }
export type Playlist = { id: string; name: string; cover: string[]; tracks: number }
export type Song = { id: string; name: string; artists: Artist[]; album: Album; time: number }
export type TauriError = { IO: string } | { Mutex: string } | { Command: string } | { Timeout: Duration } | { Tauri: string } | { RustyPipe: string }

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type Webview as __Webview__ } from "@tauri-apps/api/webview";
import { type Window as __Window__ } from "@tauri-apps/api/window";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
  ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
  : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

export function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  const result = {} as {
    [K in keyof T]: __EventObj__<T[K]> & {
      (window: __Webview__ | __Window__): __EventObj__<T[K]>;
    };
  };

  for (const key in mappings) {
    const name = mappings[key];

    const base: __EventObj__<any> = {
      listen: (cb) => TAURI_API_EVENT.listen(name, cb),
      once: (cb) => TAURI_API_EVENT.once(name, cb),
      emit: (payload: any) => TAURI_API_EVENT.emit(name, payload),
    };

    const withWindow = (window: __Webview__ | __Window__): __EventObj__<any> => ({
      listen: (cb) => window.listen(name, cb),
      once: (cb) => window.once(name, cb),
      emit: (payload: any) => window.emit(name, payload),
    });

    result[key] = Object.assign(withWindow, base);
  }

  return result;
}

